Fix compile with clang and KPIPEWIRE_DEPRECATED
Fixes:
```
error: 'deprecated' attribute cannot be applied to types
```


(cherry picked from commit e802295b53d4230e65df9265a0d3eae2921d02fd)

Co-authored-by: Allen Winter <winter@kde.org>